service: content-management-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: production
  region: us-west-1

functions:
  api:
    handler: src/handler.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'
