service: content-management-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-west-1
  
package:
  include:
    - node_modules/**

functions:
  api:
    handler: src/handler.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true
